name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        build-type: [ Debug, Release ]

    steps:
      - uses: actions/checkout@v2

      - name: Install CMake
        uses: actions/setup-cmake@v2
        with:
          cmake-version: '3.26.0'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build/${{ matrix.build-type }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build/${{ matrix.build-type }} --config ${{ matrix.build-type }}

      # Only allow pull requests to be merged into main if all checks have passed
      - name: Check for passing status
        id: check_status
        run: echo "::set-output name=status::$(if [ -z \$(git log -1 --pretty=format:'%s' | grep '\[skip ci\]\|\[ci skip\]') ]; then echo 'success'; else echo 'skipped'; fi)"

      - name: Pull request status
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-pull-request-status@v3
        with:
          context: "CI - Build"
          state: ${{ steps.check_status.outputs.status }}
          token: ${{ secrets.GITHUB_TOKEN }}

