name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        build-type: [ Debug, Release ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build/${{ matrix.build-type }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build/${{ matrix.build-type }} --config ${{ matrix.build-type }}
