name: format

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format
    - name: Pull latest code
      run: git pull
    - name: Format code
      run: |
        clang-format -i -style=file $(find src/ -name '*.cpp' -o -name '*.cc' -o -name '*.c' -o -name '*.h' -o -name '*.hpp' -o -name '*.hh') $(find include/ -name '*.h' -o -name '*.hpp' -o -name '*.hh')
    - name: Commit formatted code
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Format code with clang-format"
        git push
